name: build

on:
  push:
    branches: main
    paths-ignore: '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build:
        - { type: 'Release', name: 'release' }
        - { type: 'Debug', name: 'debug' }

    steps:
    - name: Check out
      uses: actions/checkout@v6
      with:
        fetch-depth: 1

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Setup variables
      run: |
        echo "KEY_STORE_FILE=$(pwd)/key.jks" > keystore.properties
        echo "${{ secrets.KEYSTOREPROP }}" | base64 -d >> keystore.properties
        echo "${{ secrets.KEYSTORE }}" | base64 -d > key.jks

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build ${{ matrix.build.name }}
      run: ./gradlew assemble${{ matrix.build.type }}

    - name: Upload ${{ matrix.build.name }}
      uses: actions/upload-artifact@v6
      with:
        name: ${{ matrix.build.name }}
        path: app/build/outputs/apk/${{ matrix.build.name }}/app-${{ matrix.build.name }}.apk
        compression-level: 9
